### ISSUE TITLE
Error when using bili

### ISSUE THREAD

**Issue by artyprog** [egoist/bili#124]
Hello,
I am  trying  to transpile a single vue file namely : mc.vue

Here the error I get

c:\temp\bili>**bili --plugin vue mc.vue**
×  localRequire(...) is not a function
TypeError: localRequire(...) is not a function
    at plugins.map.pluginName (C:\Users\sdidio-ccrf\AppData\Roaming\npm\node_modules\bili\dist\index.js:579:40)
    at Array.map (<anonymous>)
    at Bili.loadUserPlugins (C:\Users\sdidio-ccrf\AppData\Roaming\npm\node_modules\bili\dist\index.js:553:20)
    at Bili.<anonymous> (C:\Users\sdidio-ccrf\AppData\Roaming\npm\node_modules\bili\dist\index.js:738:238)
    at new Promise (<anonymous>)
    at Bili.createConfig (C:\Users\sdidio-ccrf\AppData\Roaming\npm\node_modules\bili\dist\index.js:643:12)
    at Bili.<anonymous> (C:\Users\sdidio-ccrf\AppData\Roaming\npm\node_modules\bili\dist\index.js:868:41)
    at new Promise (<anonymous>)
    at options.map.option (C:\Users\sdidio-ccrf\AppData\Roaming\npm\node_modules\bili\dist\index.js:865:43)
    at Array.map (<anonymous>)
    at Bili.<anonymous> (C:\Users\sdidio-ccrf\AppData\Roaming\npm\node_modules\bili\dist\index.js:865:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

Thanks for your help

regards

**Comment by egoist** [comment]
Fixed in 3.1.2
