### ISSUE TITLE
Question: compress with vue plugin?

### ISSUE THREAD

**Issue by NemoAlex** [egoist/bili#25]
I tired to:

```
bili --plugins vue --compress
```

Error:
```
{ Error: Error transforming bundle with 'uglify' plugin: Unexpected token: punc (()
    at error (/Users/Nemo/dev/workspace/vue-one-size/node_modules/rollup/dist/rollup.js:177:12)
    at /Users/Nemo/dev/workspace/vue-one-size/node_modules/rollup/dist/rollup.js:9456:5
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3 code: 'BAD_BUNDLE_TRANSFORMER', plugin: 'uglify' }
Error transforming bundle with 'uglify' plugin: Unexpected token: punc (()
error Command failed with exit code 1.
```

My project here: https://github.com/ROYL-Design/vue-one-size

**Comment by egoist** [comment]
Hmm, seems we have to insert rollup-plugin-vue before buble/babel plugin, will fix this later

**Comment by egoist** [comment]
Try 0.17.5

**Comment by NemoAlex** [comment]
```
yarn upgrade bili
yarn upgrade v0.24.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ bili@0.17.5
✨  Done in 7.29s.
Nemo@mac (master):~/dev/workspace/vue-one-size > yarn build
yarn build v0.24.5
$ bili --plugins vue --compress
'numeral' is imported by src/component.vue, but could not be resolved – treating it as an external dependency
'numeral' is imported by src/component.vue, but could not be resolved – treating it as an external dependency
Using named and default exports together. Consumers of your bundle will have to use vueOneSize['default'] to access the default export, which may not be what you want. Use `exports: 'named'` to disable this warning
Using named and default exports together. Consumers of your bundle will have to use vueOneSize['default'] to access the default export, which may not be what you want. Use `exports: 'named'` to disable this warning
{ Error: Error transforming bundle with 'uglify' plugin: Unexpected token: punc (()
    at error (/Users/Nemo/dev/workspace/vue-one-size/node_modules/rollup/dist/rollup.js:177:12)
    at /Users/Nemo/dev/workspace/vue-one-size/node_modules/rollup/dist/rollup.js:9456:5
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3 code: 'BAD_BUNDLE_TRANSFORMER', plugin: 'uglify' }
Error transforming bundle with 'uglify' plugin: Unexpected token: punc (()
error Command failed with exit code 1.
```

**Comment by egoist** [comment]
Try 0.17.7 😅

**Comment by NemoAlex** [comment]
Works fine now.
Thank you!
