### ISSUE TITLE
--format causes TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by VitorLuizC** [egoist/bili#38]
In latest bili version using `--format` option causes the error below.
```
MacBook-Pro-de-Vitor:Binance-Transactions vitorcavalcanti$ npm run build

> binance-transactions@0.0.1 build /Users/vitorcavalcanti/Projects/Binance-Transactions
> bili --format cjs,umd,umd-min

/Users/vitorcavalcanti/Projects/Binance-Transactions/node_modules/cac/dist/cac.js:248
        console.log(`The value of flag "${option.name}" should be one of: ${option.choices.map(choice => `"${choice}"`)}`);
                                                                                           ^

TypeError: Cannot read property 'map' of undefined
    at Cac.cli.on (/Users/vitorcavalcanti/Projects/Binance-Transactions/node_modules/cac/dist/cac.js:248:92)
    at Cac.emit (events.js:164:20)
    at Cac.parse (/Users/vitorcavalcanti/Projects/Binance-Transactions/node_modules/cac/dist/cac.js:409:10)
    at Object.<anonymous> (/Users/vitorcavalcanti/Projects/Binance-Transactions/node_modules/bili/lib/cli.js:55:5)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-transactions@0.0.1 build: `bili --format cjs,umd,umd-min`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-transactions@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vitorcavalcanti/.npm/_logs/2017-12-30T03_52_21_061Z-debug.log
```

**Comment by egoist** [comment]
Try reinstall bili, it should be fixed now.

**Comment by VitorLuizC** [comment]
It worked!
Thx a lot!
